### ISSUE TITLE
Fix Imports

### ISSUE THREAD

**Issue by michaelweinold** [brightway-lca/brightway-learn#35]
Imports seem to be broken. `environment.yml`

```
name: xeus-python-kernel
channels:
  - conda-forge
  - nodefaults
dependencies:
  - matplotlib:
      channels:
        - https://repo.mamba.pm/emscripten-forge
  - numpy:
      channels:
        - https://repo.mamba.pm/emscripten-forge
  - pandas:
      channels:
        - https://repo.mamba.pm/emscripten-forge
  - tqdm:
      channels:
        - conda-forge
```

gives:

<img width="689" alt="Screenshot 2023-04-12 at 13 07 39" src="https://user-images.githubusercontent.com/23102087/231439706-e102ab38-3aaa-4460-b903-694082768ccf.png">
